### ISSUE TITLE
Please improve plugins db description on moodle.org

### ISSUE THREAD

**Issue by danmarsden** [PlagiarismCheck/moodle-plagiarism_pchkorg#1]
The description in your moodle.org plugins db entry must make it very clear that your plugin requires a commercial subscription - it would also be good if you could improve it a bit to describe your service (take a look at some of the other plagiarism plugins in the plugins db for some examples)

**Comment by JaneAdelmann** [comment]
Issue has been fixed.

**Comment by danmarsden** [comment]
Thanks - that looks a lot better!
