### ISSUE TITLE
invalid install.xml file

### ISSUE THREAD

**Issue by danmarsden** [PlagiarismCheck/moodle-plagiarism_pchkorg#10]
It looks like you have hand-written your install.xml file and it is not correct/valid and may cause issues for some sites.
You need to use the built-in xmldb editor UI in Moodle to edit this file - easiest way to do this is to open it in the xmldb editor and make a change to a comment on a field or table to trigger a change - then use the xmldb editor built-in functions to save the file (you may need to change file-level permissions to allow xmldb editor to save the file.)

**Comment by JaneAdelmann** [comment]
Fixed in version v2.1
