### ISSUE TITLE
report.php seems to allow any logged in user to send "any" file to the external service.

### ISSUE THREAD

**Issue by danmarsden** [PlagiarismCheck/moodle-plagiarism_pchkorg#13]
report.php seems to allow a Moodle fileid to be passed to the script but there is no validation performed to see if the current user should have access to this file. - particular on the POST action.
This presents a security risk and you should not be using the Moodle "fileid" in this way.

The method of sending a file needs to occur in a different way so that correct user permissions are checked.

**Comment by JaneAdelmann** [comment]
Fixed in version v2.1
