### ISSUE TITLE
code precheck report

### ISSUE THREAD

**Issue by danmarsden** [PlagiarismCheck/moodle-plagiarism_pchkorg#14]
I see you have added travis ci support but have disabled the moodle codechecker test - it would be good for you to re-enable this and fix up some of these issues some of which are also reported by the plugins db code prechecks report you can see here:
https://moodle.org/plugins/pluginversions.php?plugin=plagiarism_pchkorg
(click on the code prechecks link beside the most recent version.)

**Comment by JaneAdelmann** [comment]
Fixed in version v2.1
