### ISSUE TITLE
Please state in plugins db description that submissions happen manually.

### ISSUE THREAD

**Issue by danmarsden** [PlagiarismCheck/moodle-plagiarism_pchkorg#18]
Most plagiarism plugins rely on the moodle events like assessable_submitted and automatically send submitted files to the external plagiarism service. Your plugin requires the teacher/student to click a button after they have submitted their assignment to send it to your plagiarism service (I don't see this as a bad thing) - but it should be clear in your plugins db description - something like 

"After uploading their assignment, Students/teachers are provided with a link that allows them to send the file for plagiarism checking"

**Comment by JaneAdelmann** [comment]
We completely rewrite plugin, so now it uses moodle events, as you recommend.
Thank you.
