### ISSUE TITLE
install.php isn't really needed

### ISSUE THREAD

**Issue by danmarsden** [PlagiarismCheck/moodle-plagiarism_pchkorg#22]
the install.php file allows you to trigger extra things on install of the plugin - like adding stuff to db tables, enabling settings etc. You have a xmldb_plagiarism_pchkorg_install function which just returns true/false - but this isn't needed at all.

You might want to just delete the install.php file because it's not really doing anything.

This doesn't block approval in the plugins db - just looks weird :-)

**Comment by JaneAdelmann** [comment]
File has been deleted
