### ISSUE TITLE
English language strings are not available in AMOS

### ISSUE THREAD

**Issue by germanvaleroelizondo** [PlagiarismCheck/moodle-plagiarism_pchkorg#23]
This plugin does not have its English language strings available for translation in AMOS.
Please check https://docs.moodle.org/dev/Plugin_contribution_checklist#Strings

**Comment by JaneAdelmann** [comment]
This issue has been fixed. 
Thank you for your contribution.

**Comment by germanvaleroelizondo** [comment]
Now AMOS has the English strings for translation.
Thanks.
