### ISSUE TITLE
The 'name' value must be set in other

### ISSUE THREAD

**Issue by leonstr** [PlagiarismCheck/moodle-plagiarism_pchkorg#25]
With Moodle 4.0.2 or later, when saving changes to an activity the error _Coding error detected, it must be fixed by a programmer: The 'name' value must be set in other._ appears.

To reproduce this:

1. Create a course.
2. Add a label (mod_label) to the course.
3. Edit the label changing the text and click _Save and return to course_.

Results (with debugging enabled):
```
Coding error detected, it must be fixed by a programmer: The 'name' value must be set in other.

More information about this error
Debug info:
Error code: codingerror
Stack trace:

    line 136 of /lib/classes/event/course_module_updated.php: coding_exception thrown
    line 272 of /lib/classes/event/base.php: call to core\event\course_module_updated->validate_data()
    line 161 of /lib/classes/event/course_module_updated.php: call to core\event\base::create()
    line 693 of /course/modlib.php: call to core\event\course_module_updated::create_from_cm()
    line 168 of /course/modedit.php: call to update_moduleinfo()
```

**Comment by leonstr** [comment]
This issue arises following change MDL-74533 in Moodle 4.0.2 (1ecfc86) where [the course_module_updated event is created after the plagiarism plugin callback instead of before](https://github.com/moodle/moodle/commit/1ecfc86f97a283f9f3815976a212c34acb019f8a#diff-7abd2647520ce56c5ab9f7bf1e1fb61049c219332858b5ce3771d83875029918).

Removing the empty function **plagiarism_pchkorg_coursemodule_edit_post_actions()** in **plagiarism/pchkorg/lib.php** and purging caches fixes the problem.

**Comment by leonstr** [comment]
Pull request added https://github.com/PlagiarismCheck/moodle-plagiarism_pchkorg/pull/26

**Comment by tahirulamin** [comment]
plz guide how to perform it
Removing the empty function plagiarism_pchkorg_coursemodule_edit_post_actions() in plagiarism/pchkorg/lib.php and purging caches fixes the problem.

**Comment by tahirulamin** [comment]
function plagiarism_pchkorg_coursemodule_edit_post_actions($data, $course)
{   global $DB;
    $pchkorgconfigmodel = new plagiarism_pchkorg_config_model();

    $config = $pchkorgconfigmodel->get_system_config('pchkorg_use');
    if ('1' != $config) {
        return;
 
    }

**Comment by JaneAdelmann** [comment]
This issue has been fixed with version  3.11.2

**Comment by leonstr** [comment]
@tahirulamin Try changing line 201 of **lib.php** from `return;` to `return $data;`. See #27 for more information, I opened that new issue as it's a slightly different manifestation of this original issue.

**Comment by JaneAdelmann** [comment]
The version of moodle plugin v3.11.3 has this line changed. 
https://github.com/PlagiarismCheck/moodle-plagiarism_pchkorg/blob/master/lib.php#L201
You can just update your version of moodle plugin. 

Thank you for cooperation.
