### ISSUE TITLE
functions and classes should be namespaced or prefixed with the plugin name

### ISSUE THREAD

**Issue by danmarsden** [PlagiarismCheck/moodle-plagiarism_pchkorg#4]
All classes should be namespaced or prefixed with the plugin name - eg:
"FileModel" should either be named :
plagiarism_pchkorg_filemodel or namespaced within plagiarism/pchkorg

But - your use of classes is quite strange in terms of Moodle coding guidelines - it would be better not to abstract things like FileModel::create and just put the code to insert the record in the in-line code instead of abstracted out into a class function.

Ideally it would be good to remove your ConfigModel/filemodel classes completely and use more Moodle style php.

**Comment by danmarsden** [comment]
another example:
class plagiarism_setup_form 
should be more like:
class plagiarism_pchkorg_setup_form

**Comment by JaneAdelmann** [comment]
Fixed in version v2.1
