### ISSUE TITLE
missing privacy api.

### ISSUE THREAD

**Issue by danmarsden** [PlagiarismCheck/moodle-plagiarism_pchkorg#9]
Moodle uses a privacy API for GDPR compliance to allow plugins to specify how they deal with user data. At the very least you will need to implement the external_link functions of the privacy api to disclose that you pass private user information to an external service.

Sites that use continuous integration processes will not be able to use your plugin because Moodle runs unit tests which check to see if all extra plugins include the privacy class.

More information on the privacy class is here:
https://docs.moodle.org/dev/Privacy_API

**Comment by JaneAdelmann** [comment]
Fixed in version v2.1
